- hosts: bastion
  # remote_user: yoshizawa.takayuki
  # sudo: yes
  gather_facts: no
  vars:
    ansible_ssh_user: '{{ login_user }}'
    ansible_ssh_pass: '{{ password }}'
    ansible_sudo_pass: '{{ password }}'
  tasks:
    - name: hoge
      shell: echo 25 > test.txt

    - name: kinit
      shell: |
        spawn kinit
        expect "Password for *"
        send -- '{{ password }}'
        exit 0