- name: test and build daemon server
  hosts: 127.0.0.1
  connection: local
  vars:
    # ansible_ssh_user: '{{ login_user }}'
    # ansible_ssh_pass: '{{ password }}'
    # ansible_sudo_pass: '{{ password }}'
    bash_profile_path: ~/.bash_profile
    local_bin_path: export PATH=/usr/local/bin/:${PATH}
    sbin_path: export PATH=/usr/sbin/:${PATH}
  tasks:
    - name: test and build
      shell: |
        npm test
        npm run build
      register: return_from_shell
      changed_when: no

    - name: show previous shell stdout
      debug:
        msg: "{{ return_from_shell.stdout }}"

    - name: deploy and restart systemd
      hosts: webservers
      tasks:
        - name: copy
          copy:
            src: /home/hoge
            dest: /home/
            force: yes

    - name: restart daemon
      systemd:
        state: restarted
        name: daemon_something
        enabled: true
      become: true

    - name: add {{local_bin_path}} to path
      shell: |
        TARGET_STR=`cat {{ bash_profile_path }} | grep '{{ local_bin_path }}'`
        if [ -z "$TARGET_STR" ]; then
          echo '{{ local_bin_path }}' >> {{ bash_profile_path }}
        fi

    - name: add {{sbin_path}} to path
      shell: |
        TARGET_STR=`cat {{ bash_profile_path }} | grep '{{ sbin_path }}'`
        if [ -z "$TARGET_STR" ]; then
          echo '{{ sbin_path }}' >> {{ bash_profile_path }}
        fi
