- name: test and build daemon server
  hosts: 127.0.0.1
  connection: local
  vars:
    # ansible_ssh_user: '{{ login_user }}'
    # ansible_ssh_pass: '{{ password }}'
    # ansible_sudo_pass: '{{ password }}'  
  tasks:
    - name: test and build
      shell: |
        npm test
        npm run build
      register: return_from_shell
      changed_when: no

    - name: show previous shell stdout
      debug:
        msg: "{{ return_from_shell.stdout }}"

- name: deploy and restart systemd
  hosts: webservers
  tasks:
    - name: copy
      copy:
        src: /home/hoge
        dest: /home/
        force: yes

    - name: restart daemon
      systemd:
        state: restarted
        name: daemon_something
        enabled: true
      become: true